In [36]:
# Import Dependencies
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [37]:
# Name of the CSV file
file = './Resources/MRTS-mf_data.csv'

In [38]:
data_df = pd.read_csv(file, encoding="ISO-8859-1", low_memory=False)

In [39]:
data_df.head()

per_idx  cat_idx  dt_idx  et_idx  geo_idx  is_adj     val
0        1        5       1       0        1       0  130683
1        1        5       1       0        1       1  146925
2        1        6       1       0        1       0  100872
3        1        6       1       0        1       1  113447
4        1        7       1       0        1       0   33906

In [40]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165961 entries, 0 to 165960
Data columns (total 7 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   per_idx  165961 non-null  int64 
 1   cat_idx  165961 non-null  int64 
 2   dt_idx   165961 non-null  int64 
 3   et_idx   165961 non-null  int64 
 4   geo_idx  165961 non-null  int64 
 5   is_adj   165961 non-null  int64 
 6   val      165961 non-null  object
dtypes: int64(6), object(1)
memory usage: 8.9+ MB


In [41]:
#drop all vaules that aren't adjested for the holidays
data_df = data_df[data_df.is_adj != 0]
data_df['is_adj'].unique()

array([1], dtype=int64)

In [42]:
#check the amount of row with errors
data_df['et_idx'].value_counts()

0    36911
1    15131
5    15131
2     2232
3     2232
4     2232
Name: et_idx, dtype: int64

In [43]:
#drop all vaules with known errors
data_df = data_df[data_df.et_idx == 0]
data_df['et_idx'].unique()

array([0], dtype=int64)

In [44]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36911 entries, 1 to 165954
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   per_idx  36911 non-null  int64 
 1   cat_idx  36911 non-null  int64 
 2   dt_idx   36911 non-null  int64 
 3   et_idx   36911 non-null  int64 
 4   geo_idx  36911 non-null  int64 
 5   is_adj   36911 non-null  int64 
 6   val      36911 non-null  object
dtypes: int64(6), object(1)
memory usage: 2.3+ MB


In [45]:
options = [27,28,29,32,46,47,48,49,61,62,63,64]
  
# selecting rows based on condition
data_df_reduced = data_df.loc[data_df['cat_idx'].isin(options)]
data_df_reduced['cat_idx'].unique()

array([27, 28, 32, 46, 47, 61], dtype=int64)

In [46]:
data_df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7530 entries, 31 to 165954
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   per_idx  7530 non-null   int64 
 1   cat_idx  7530 non-null   int64 
 2   dt_idx   7530 non-null   int64 
 3   et_idx   7530 non-null   int64 
 4   geo_idx  7530 non-null   int64 
 5   is_adj   7530 non-null   int64 
 6   val      7530 non-null   object
dtypes: int64(6), object(1)
memory usage: 470.6+ KB
