In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import file
file = './Resources/MRTS-mf_data.csv'
data_df = pd.read_csv(file, encoding="ISO-8859-1", low_memory=False)
data_df.head()

per_idx  cat_idx  dt_idx  et_idx  geo_idx  is_adj     val
0        1        5       1       0        1       0  130683
1        1        5       1       0        1       1  146925
2        1        6       1       0        1       0  100872
3        1        6       1       0        1       1  113447
4        1        7       1       0        1       0   33906

In [3]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165961 entries, 0 to 165960
Data columns (total 7 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   per_idx  165961 non-null  int64 
 1   cat_idx  165961 non-null  int64 
 2   dt_idx   165961 non-null  int64 
 3   et_idx   165961 non-null  int64 
 4   geo_idx  165961 non-null  int64 
 5   is_adj   165961 non-null  int64 
 6   val      165961 non-null  object
dtypes: int64(6), object(1)
memory usage: 8.9+ MB


In [4]:
#drop all vaules that aren't adjested for the holidays
data_df = data_df[data_df.is_adj != 0]
data_df['is_adj'].unique()

array([1], dtype=int64)

In [5]:
#check for row with errors
data_df['et_idx'].value_counts()

0    36911
1    15131
5    15131
2     2232
3     2232
4     2232
Name: et_idx, dtype: int64

In [6]:
#drop all vaules with known errors
data_df = data_df[data_df.et_idx == 0]
data_df['et_idx'].unique()

array([0], dtype=int64)

In [7]:
#verify that row with no errors remain
data_df['et_idx'].value_counts()

0    36911
Name: et_idx, dtype: int64

In [8]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36911 entries, 1 to 165954
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   per_idx  36911 non-null  int64 
 1   cat_idx  36911 non-null  int64 
 2   dt_idx   36911 non-null  int64 
 3   et_idx   36911 non-null  int64 
 4   geo_idx  36911 non-null  int64 
 5   is_adj   36911 non-null  int64 
 6   val      36911 non-null  object
dtypes: int64(6), object(1)
memory usage: 2.3+ MB


In [9]:
options = [27,28,29,32,46,47,48,49,61,62,63,64]
  
# selecting rows based on condition
data_df_reduced = data_df.loc[data_df['cat_idx'].isin(options)]
data_df_reduced['cat_idx'].unique()

array([27, 28, 32, 46, 47, 61], dtype=int64)

In [10]:
#reset index
data_df_reduced = data_df_reduced.reset_index()

In [11]:
data_df_reduced

index  per_idx  cat_idx  dt_idx  et_idx  geo_idx  is_adj    val
0         31        1       27       1       0        1       1  30437
1         33        1       28       1       0        1       1  27835
2         39        1       32       1       0        1       1   6461
3         69        1       46       1       0        1       1  19879
4         73        1       47       1       0        1       1  14134
...      ...      ...      ...     ...     ...      ...     ...    ...
7525  165877      359       47       5       0        1       1   -5.5
7526  165885      359       61       5       0        1       1    0.6
7527  165951      359       27       4       0        1       1    0.4
7528  165953      359       46       4       0        1       1    0.8
7529  165954      359       47       4       0        1       1    1.5

[7530 rows x 8 columns]

In [12]:
data_df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7530 entries, 0 to 7529
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   index    7530 non-null   int64 
 1   per_idx  7530 non-null   int64 
 2   cat_idx  7530 non-null   int64 
 3   dt_idx   7530 non-null   int64 
 4   et_idx   7530 non-null   int64 
 5   geo_idx  7530 non-null   int64 
 6   is_adj   7530 non-null   int64 
 7   val      7530 non-null   object
dtypes: int64(7), object(1)
memory usage: 470.8+ KB


Renaming Values in the Columns

In [13]:
#convert the catagorey index into a string
data_df_reduced['cat_idx'] = data_df_reduced['cat_idx'].astype('string')

In [14]:
data_df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7530 entries, 0 to 7529
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   index    7530 non-null   int64 
 1   per_idx  7530 non-null   int64 
 2   cat_idx  7530 non-null   string
 3   dt_idx   7530 non-null   int64 
 4   et_idx   7530 non-null   int64 
 5   geo_idx  7530 non-null   int64 
 6   is_adj   7530 non-null   int64 
 7   val      7530 non-null   object
dtypes: int64(6), object(1), string(1)
memory usage: 470.8+ KB


In [15]:
data_df_reduced['cat_idx'].replace({"27": "Grocery"}, inplace=True)
data_df_reduced['cat_idx']

0       Grocery
1            28
2            32
3            46
4            47
         ...   
7525         47
7526         61
7527    Grocery
7528         46
7529         47
Name: cat_idx, Length: 7530, dtype: object

In [16]:
data_df_reduced.head()

index  per_idx  cat_idx  dt_idx  et_idx  geo_idx  is_adj    val
0     31        1  Grocery       1       0        1       1  30437
1     33        1       28       1       0        1       1  27835
2     39        1       32       1       0        1       1   6461
3     69        1       46       1       0        1       1  19879
4     73        1       47       1       0        1       1  14134

In [17]:
data_df_reduced['cat_idx'].replace({"28": "Grocery", 
                                    "32": "Pharmacy",
                                    "46": "General Merchandise",
                                    "47": "General Merchandise",
                                    "61": "Restaurants"}, inplace=True)
data_df_reduced['cat_idx']

0                   Grocery
1                   Grocery
2                  Pharmacy
3       General Merchandise
4       General Merchandise
               ...         
7525    General Merchandise
7526            Restaurants
7527                Grocery
7528    General Merchandise
7529    General Merchandise
Name: cat_idx, Length: 7530, dtype: object

In [18]:
data_df_reduced.head()

index  per_idx              cat_idx  dt_idx  et_idx  geo_idx  is_adj    val
0     31        1              Grocery       1       0        1       1  30437
1     33        1              Grocery       1       0        1       1  27835
2     39        1             Pharmacy       1       0        1       1   6461
3     69        1  General Merchandise       1       0        1       1  19879
4     73        1  General Merchandise       1       0        1       1  14134

## Populate the Dates from the Lookup Table

In [19]:
file_2 = './Resources/time-pds.csv'
time_df = pd.read_csv(file_2, encoding="ISO-8859-1", low_memory=False)
time_df.head()

per_idx per_name
0       1   Jan-92
1       2   Feb-92
2       3   Mar-92
3       4   Apr-92
4       5   May-92

In [20]:
time_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   per_idx   360 non-null    object
 1   per_name  359 non-null    object
dtypes: object(2)
memory usage: 5.8+ KB


In [21]:
time_df['per_idx'] = data_df_reduced['per_idx'].astype('int64')

In [23]:
time_df

per_idx per_name
0          1   Jan-92
1          1   Feb-92
2          1   Mar-92
3          1   Apr-92
4          1   May-92
..       ...      ...
355       18   21-Aug
356       18   21-Sep
357       18   21-Oct
358       18   21-Nov
359       18      NaN

[360 rows x 2 columns]